server:
  port: 8080  # Server port configuration

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehiclemanagment # Replace with your MySQL database URL
    username: root  # Your MySQL username
    password:   # Your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver class
  jpa:
    hibernate:
      ddl-auto: update  # For development, use 'update'; in production, consider 'validate' or 'none'
    show-sql: true  # Shows SQL queries in the logs
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL dialect for Hibernate

    properties:

        format_sql: true
# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG  # Enables debug logging for Spring Web
